### ISSUE TITLE
TIP 6.0 terminology

### ISSUE THREAD

**Issue by Untit1ed** [tip-initiative/tip-initiative-apis#164]
Could you provide some additional information on the new `Creative` common type and what can it be used for.  Its current description is very abstract "Object representing the creative".

From the new json samples it looks like `AdId` is moved into the Creative Ids now. What else can be stored in there?

I would also appreciate if you could explain the new `Unit.bookedLength` property. How does it differ from the `airedLength`?

**Comment by touficmoubarak** [comment]
Correct.  The creative asset object was created to hold information regarding the actual media asset. 
In addition to Ad-Id, Properties like length, and status, the Format object can be used in conjunction to provide more technical details about the asset like aspect ratio,  bit rate etc.

The complete creative asset is used in the unreleased endpoint creativeAsset.

**Comment by touficmoubarak** [comment]
Mistakenly said unreleased Creative asset endpoint. Buyer/CreativeAssets allows creative companies to send information concerning the creative assets to aid in receiving, dibbing, transcoding, and playback,  etc.

**Comment by touficmoubarak** [comment]
I noticed that I didn't answer your question concerning bookedLength vs airedLength. As explained by some vendors, particularly in logtimes, that on occasions the sales booked :30 seconds spot but when the unit aired for 29 seconds only. 

Your request appeared from untitled. Can I ask you who you are working with. Can you share your contact? Feel free reach out directly using  toufic at frontrowadvisory dot com

**Comment by Untit1ed** [comment]
Thank you for the reply, Toufic. My name is Maksim (mvarin at provantagex dot com), I work with ProVantageX. I'm updating our endpoints to support the latest TIP version.

I'm particularly interested in `/seller/logTimes` endpoint, and so far it doesn't look like CreativeAssets are going to affect my work, but I'd be interested to find the best way to extract AdId from posted logtimes.

In a provided example there is a unit being sent with a creative that has 2 ids:
https://github.com/tip-initiative/tip-initiative-apis/blob/2e3c15b6685f042803acf59e6e5f6c3a0092bcb1/endpoints/examples/6.0.0/Seller/JSON/LogtimesNew.json#L116-L134

Judging by 5.1 example: 
https://github.com/tip-initiative/tip-initiative-apis/blob/2e3c15b6685f042803acf59e6e5f6c3a0092bcb1/endpoints/examples/5.1.0/SellerLogtimesNew.json#L60

the id I'm looking for is `HYUN1234` (AdId from 5.1), but it seems like there's currently no way for a seller to indicate which one of 2 provided creative ids is an AdId.

**Comment by touficmoubarak** [comment]
Thanks for your response. I received your email as well. Here the difference between 5.1.0 and 6.0.0. Version 5.1.0 didn't allow for providing multiple IDs for many objects. That's why logtimes in 5.0.1 allowed only for one ID with no explanation concerning the source of that ID. In 6.0.0, most IDs make use an array of a common object called 'Identifier'. The Identifier object allows for the sender the option to provide multiple IDs for the object. the IDs are distinguished by the ID of their owner (srcId) and the name of that owner (srcName). Back to example in 6.0.0, the first Id in the 'creative' object is owned by 'KHOU-TV' which means it could be their internal legacy 'House Number', the second id it's owner is identified as 'Ad-id.org' and it's srcName="Ad ID code'. That said the true AdId registered at Ad-Id.org is id='ABCD000123H'. this Id also matches the pattern defined for AdId in commonSchemas.yaml
