### ISSUE TITLE
TransactionId type change request

### ISSUE THREAD

**Issue by Untit1ed** [tip-initiative/tip-initiative-apis#94]
`#/components/schemas/TransactionId`:
> a system generated unique number for each data exchange. The **transactionNum** (typo?) is generated by the system that is creating the data exchange

In the spec it's defined as an integer, however most of the systems pass it as a GUID/string. Any plans to change its type to string?

Also on `TransactionHeader` it is not marked as required, because of a previous renaming it still lists obsolete `transactionNum` as a required field:

```
TransactionHeader:
      description: A common object defining the general transaction header information
      properties:
        tipVersion:
          description: TIP version of the interface
          type: string
        transactionId:
          $ref: '#/components/schemas/TransactionId'
      ...
      required:
        - tipVersion
        - transactionNum
        - timeStamp
```

**Comment by touficmoubarak** [comment]
good catch. thanks for this remark. fixed in both places. I agree regarding the GUID vs Integer. I don't recall anyone objecting to it being an integer. I will ask James and Heather to raise out with other vendors. my preference is to make it a coded integer like YYDDMMxxxxxx where xxxxx is sequential number.
